#!/usr/bin/env bash
set -e

echo "⚙️ Extending Vire Platform (CLI + Export + Phase-2 Build)"

ROOT="vire-agent"
CLI="$ROOT/cli"
EXPORT="$ROOT/export"
BUILD="$ROOT/build"

mkdir -p "$CLI" "$EXPORT/pages" "$BUILD"

# --------------------------------------------------
# 1️⃣ VIRE CLI
# --------------------------------------------------
cat <<'PY' > "$CLI/vire.py"
#!/usr/bin/env python3
import json, sys, requests

if len(sys.argv) < 2:
    print("Usage: vire <site.json>")
    sys.exit(1)

with open(sys.argv[1]) as f:
    spec = json.load(f)

res = requests.post(
    "http://localhost:7070/generate-site",
    json=spec,
    timeout=30
)

if res.status_code != 200:
    print("❌ Generation failed:", res.text)
    sys.exit(1)

data = res.json()
print("✅ Site generated:", data["site_id"])
print("Pages:", ", ".join(data["pages_created"]))
PY

chmod +x "$CLI/vire.py"

cat <<'SH' > "$CLI/vire"
#!/usr/bin/env bash
python3 "$(dirname "$0")/vire.py" "$@"
SH

chmod +x "$CLI/vire"

# --------------------------------------------------
# 2️⃣ STATIC EXPORT → WORDPRESS IMPORT
# --------------------------------------------------
cat <<'PY' > "$EXPORT/wp_static_export.py"
import os, json

BASE = os.path.dirname(__file__)
PAGES = os.path.join(BASE, "pages")
os.makedirs(PAGES, exist_ok=True)

def export_page(title, content):
    slug = title.lower().replace(" ", "-")
    html = f"""
<!-- wp:group -->
<div class="wp-block-group">
{content}
</div>
<!-- /wp:group -->
"""
    with open(os.path.join(PAGES, f"{slug}.html"), "w") as f:
        f.write(html)

if __name__ == "__main__":
    if not os.path.exists("site.json"):
        raise SystemExit("❌ site.json not found in current directory")

    site = json.load(open("site.json"))
    for page in site["pages"]:
        export_page(page, f"<h1>{page}</h1><p>Generated by Vire</p>")

    print("✅ Exported Gutenberg-ready HTML to export/pages/")
PY

# --------------------------------------------------
# 3️⃣ PHASE-2 BUILD SYSTEM (NO CDN)
# --------------------------------------------------
cat <<'JS' > "$BUILD/tailwind.config.js"
module.exports = {
  content: ["../**/*.html"],
  theme: {
    extend: {
      colors: {
        primary: "#3b82f6",
        slatebg: "#020617"
      }
    }
  },
  plugins: []
}
JS

cat <<'CSS' > "$BUILD/input.css"
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --accent: #3b82f6;
  --bg: #020617;
}
CSS

cat <<'SH' > "$BUILD/build.sh"
#!/usr/bin/env bash
set -e
npx tailwindcss -c tailwind.config.js -i input.css -o ../export/styles.css --minify
echo "✅ Phase-2 CSS compiled"
SH

chmod +x "$BUILD/build.sh"

# --------------------------------------------------
# DONE
# --------------------------------------------------
echo
echo "🎉 Vire Platform Extension COMPLETE"
echo "CLI:        ./vire-agent/cli/vire"
echo "Export dir: ./vire-agent/export/pages/"
echo "Build CSS:  ./vire-agent/build/build.sh"
