#!/usr/bin/env bash
set -euo pipefail

echo "🚀 Installing Vire V5 (One command: prompt → local WP → deploy → verify → screenshot report)"

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
VIRE_ROOT="$ROOT_DIR/vire-agent"
V5="$VIRE_ROOT/v5"

TOOLS_DIR="$ROOT_DIR/vireoka-tools"
LOCAL_WP_DIR="$ROOT_DIR/vireoka_local"

mkdir -p "$V5"/{bin,gen,wp,deploy,verify,report,outputs,tmp}

# -----------------------------
# Shared utils
# -----------------------------
cat <<'SH' > "$V5/bin/common.sh"
#!/usr/bin/env bash
set -euo pipefail

ts() { date -u +"%Y-%m-%dT%H:%M:%SZ"; }

die() { echo "❌ $*" >&2; exit 1; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing command: $1"
}

# Find container by exact name
container_running() {
  local name="$1"
  docker ps --format '{{.Names}}' | grep -q "^${name}$"
}

ensure_wp_cli_in_container() {
  local wp_container="$1"
  # wp-cli isn't included in wordpress:php8.2-apache
  if docker exec "$wp_container" sh -lc "command -v wp >/dev/null 2>&1"; then
    return 0
  fi

  echo "🧰 Installing WP-CLI inside container: $wp_container"
  docker exec "$wp_container" sh -lc "php -v >/dev/null 2>&1" || die "PHP missing in container?"
  docker exec "$wp_container" sh -lc "curl -fsSL -o /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
  docker exec "$wp_container" sh -lc "chmod +x /usr/local/bin/wp && wp --info >/dev/null"
}

# Simple curl check
http_ok() {
  local url="$1"
  curl -fsSL -o /dev/null "$url"
}
SH
chmod +x "$V5/bin/common.sh"

# -----------------------------
# 1) Prompt → site.json generator
# -----------------------------
cat <<'PY' > "$V5/gen/prompt_to_site.py"
#!/usr/bin/env python3
import json, os, re, sys, datetime
from pathlib import Path

def utc_now_iso():
    return datetime.datetime.now(datetime.timezone.utc).isoformat()

def slugify(s: str) -> str:
    s = (s or "").strip().lower()
    s = re.sub(r"[^a-z0-9\s-]", "", s)
    s = re.sub(r"\s+", "-", s).strip("-")
    return s or "site"

def heuristic_site(prompt: str, product: str, tone: str):
    # Deterministic fallback if no LLM key is present
    product_name = product.strip() if product.strip() else "Vireoka Product"
    pages = ["Home", "Products", "Pricing", "Enterprise", "About", "Contact"]
    return {
        "generated_at": utc_now_iso(),
        "site_id": slugify(product_name),
        "product_name": product_name,
        "tone": tone or "elite-neural-luxe",
        "prompt": prompt,
        "pages": pages,
        "sections": {
            "Home": ["Hero", "Ecosystem Grid", "Why Agents", "Waitlist CTA", "Footer"],
            "Products": ["Bento Grid", "Feature Cards", "Security/Trust", "CTA"],
            "Pricing": ["Plans", "Comparison", "FAQ", "Enterprise CTA"],
            "Enterprise": ["Request Demo", "Security", "SLA", "Contact"],
            "About": ["Founder Note", "Mission", "Roadmap", "CTA"],
            "Contact": ["Form", "Emails", "Partnerships"]
        }
    }

def main():
    if len(sys.argv) < 2:
        print("Usage: prompt_to_site.py \"<prompt>\" [product_name] [tone] [out_path]")
        sys.exit(1)

    prompt = sys.argv[1]
    product = sys.argv[2] if len(sys.argv) > 2 else "Vireoka Product"
    tone = sys.argv[3] if len(sys.argv) > 3 else "elite-neural-luxe"
    out_path = Path(sys.argv[4]) if len(sys.argv) > 4 else Path("vire-agent/v5/outputs/site.json")
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # If you later wire an LLM, keep the same schema. For now we use deterministic output.
    site = heuristic_site(prompt, product, tone)
    out_path.write_text(json.dumps(site, indent=2), encoding="utf-8")
    print(f"✅ site.json written: {out_path}")

if __name__ == "__main__":
    main()
PY
chmod +x "$V5/gen/prompt_to_site.py"

# -----------------------------
# 2) Generate Gutenberg-ready HTML pages
# -----------------------------
cat <<'PY' > "$V5/wp/wp_static_export.py"
#!/usr/bin/env python3
import json, re, datetime
from pathlib import Path

def utc_now_iso():
    return datetime.datetime.now(datetime.timezone.utc).isoformat()

def slugify(s: str) -> str:
    s = (s or "").strip().lower()
    s = re.sub(r"[^a-z0-9\s-]", "", s)
    s = re.sub(r"\s+", "-", s).strip("-")
    return s or "page"

def page_html(title: str, product: str, tone: str):
    # Gutenberg wrapper: group block
    return f"""<!-- wp:group {{"className":"vire-site vire-product--{slugify(product)} vire-tone--{slugify(tone)}","layout":{{"type":"constrained"}}}} -->
<div class="wp-block-group vire-site vire-product--{slugify(product)} vire-tone--{slugify(tone)}">
  <!-- wp:heading {{"level":1}} -->
  <h1>{title}</h1>
  <!-- /wp:heading -->

  <!-- wp:paragraph -->
  <p><strong>{product}</strong> — generated by Vire V5 at {utc_now_iso()}.</p>
  <!-- /wp:paragraph -->

  <!-- wp:html -->
  <div class="vire-neural-host"><canvas class="vire-neural-canvas" aria-hidden="true"></canvas></div>
  <!-- /wp:html -->

  <!-- wp:columns -->
  <div class="wp-block-columns">
    <!-- wp:column -->
    <div class="wp-block-column">
      <!-- wp:heading {{"level":2}} --><h2>Why this matters</h2><!-- /wp:heading -->
      <!-- wp:paragraph --><p>Premium, enterprise-ready AI agent platform branding with Elite Neural Luxe design tokens.</p><!-- /wp:paragraph -->
    </div>
    <!-- /wp:column -->
    <!-- wp:column -->
    <div class="wp-block-column">
      <!-- wp:heading {{"level":2}} --><h2>Next steps</h2><!-- /wp:heading -->
      <!-- wp:list -->
      <ul>
        <li>Deploy to Hostinger</li>
        <li>Verify live pages</li>
        <li>Generate screenshot report</li>
      </ul>
      <!-- /wp:list -->
      <!-- wp:paragraph --><p><a class="vire-cta" href="/contact/">Request demo</a></p><!-- /wp:paragraph -->
    </div>
    <!-- /wp:column -->
  </div>
  <!-- /wp:columns -->
</div>
<!-- /wp:group -->
"""

def main():
    site_path = Path("vire-agent/v5/outputs/site.json")
    if not site_path.exists():
        raise SystemExit("❌ Missing vire-agent/v5/outputs/site.json (generate it first).")

    site = json.loads(site_path.read_text(encoding="utf-8"))
    product = site.get("product_name", "Vireoka Product")
    tone = site.get("tone", "elite-neural-luxe")
    pages = site.get("pages", ["Home"])

    out_dir = Path("vire-agent/v5/outputs/pages")
    out_dir.mkdir(parents=True, exist_ok=True)

    created = []
    for title in pages:
        slug = slugify(title)
        p = out_dir / f"{slug}.html"
        p.write_text(page_html(title, product, tone), encoding="utf-8")
        created.append(str(p))

    print("✅ Exported pages:")
    for c in created:
        print(" -", c)

if __name__ == "__main__":
    main()
PY
chmod +x "$V5/wp/wp_static_export.py"

# -----------------------------
# 3) V2 neural canvas JS (lightweight) + CSS tokens (Elite Neural Luxe)
# -----------------------------
cat <<'JS' > "$V5/wp/neural-canvas.js"
/* Vire Neural Canvas (V5) - lightweight, prefers-reduced-motion aware */
(function () {
  const reduce = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  if (reduce) return;

  function qs(sel, root = document) { return root.querySelector(sel); }

  const host = qs('.vire-neural-host');
  const canvas = qs('.vire-neural-canvas');
  if (!host || !canvas) return;

  const ctx = canvas.getContext('2d', { alpha: true });

  function cssVar(name, fallback) {
    const v = getComputedStyle(document.documentElement).getPropertyValue(name).trim();
    return v || fallback;
  }

  function resize() {
    const w = Math.max(320, host.clientWidth);
    const h = Math.max(200, Math.min(520, Math.floor(window.innerHeight * 0.38)));
    canvas.width = Math.floor(w * devicePixelRatio);
    canvas.height = Math.floor(h * devicePixelRatio);
    canvas.style.width = w + 'px';
    canvas.style.height = h + 'px';
    ctx.setTransform(devicePixelRatio, 0, 0, devicePixelRatio, 0, 0);
  }

  const nodes = [];
  function init() {
    nodes.length = 0;
    const w = host.clientWidth;
    const h = parseFloat(getComputedStyle(canvas).height);
    const n = Math.max(18, Math.min(44, Math.floor(w / 30)));
    for (let i = 0; i < n; i++) {
      nodes.push({
        x: Math.random() * w,
        y: Math.random() * h,
        vx: (Math.random() - 0.5) * 0.35,
        vy: (Math.random() - 0.5) * 0.25,
        r: 1 + Math.random() * 1.6
      });
    }
  }

  let t = 0;
  function step() {
    const w = host.clientWidth;
    const h = parseFloat(getComputedStyle(canvas).height);

    const purple = cssVar('--vire-neural-purple', '#5A2FE3');
    const teal = cssVar('--vire-electric-teal', '#3AF4D3');
    const gold = cssVar('--vire-quantum-gold', '#E4B448');

    ctx.clearRect(0, 0, w, h);

    const g = ctx.createLinearGradient(0, 0, w, h);
    g.addColorStop(0, 'rgba(90,47,227,0.16)');
    g.addColorStop(0.55, 'rgba(58,244,211,0.08)');
    g.addColorStop(1, 'rgba(228,180,72,0.10)');
    ctx.fillStyle = g;
    ctx.fillRect(0, 0, w, h);

    for (const p of nodes) {
      p.x += p.vx; p.y += p.vy;
      if (p.x < -10) p.x = w + 10;
      if (p.x > w + 10) p.x = -10;
      if (p.y < -10) p.y = h + 10;
      if (p.y > h + 10) p.y = -10;
    }

    ctx.lineWidth = 1;
    for (let i = 0; i < nodes.length; i++) {
      for (let j = i + 1; j < nodes.length; j++) {
        const a = nodes[i], b = nodes[j];
        const dx = a.x - b.x, dy = a.y - b.y;
        const d2 = dx * dx + dy * dy;
        if (d2 < 140 * 140) {
          const alpha = 1 - Math.sqrt(d2) / 140;
          ctx.strokeStyle = `rgba(90,47,227,${alpha * 0.18})`;
          ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(b.x, b.y); ctx.stroke();
        }
      }
    }

    for (const p of nodes) {
      const pulse = (Math.sin(t / 32 + p.x / 40) + 1) / 2;
      const rad = p.r + pulse * 1.2;

      ctx.beginPath();
      ctx.fillStyle = `rgba(58,244,211,${0.20 + pulse * 0.25})`;
      ctx.arc(p.x, p.y, rad, 0, Math.PI * 2);
      ctx.fill();

      ctx.beginPath();
      ctx.fillStyle = `rgba(228,180,72,${0.08 + pulse * 0.12})`;
      ctx.arc(p.x, p.y, rad * 2.1, 0, Math.PI * 2);
      ctx.fill();
    }

    t++;
    requestAnimationFrame(step);
  }

  resize();
  init();
  window.addEventListener('resize', () => { resize(); init(); }, { passive: true });
  requestAnimationFrame(step);
})();
JS

cat <<'CSS' > "$V5/wp/vire-v5.css"
/* Vire V5 tokens + Gutenberg-friendly styling (Elite Neural Luxe) */
:root{
  --vire-deep-blue:#0A1A4A;
  --vire-neural-purple:#5A2FE3;
  --vire-quantum-gold:#E4B448;
  --vire-midnight-slate:#1B2235;
  --vire-mist-gray:#C7CBD4;
  --vire-graphite:#3E465D;
  --vire-electric-teal:#3AF4D3;

  --vire-radius-md:12px;
  --vire-radius-lg:20px;

  --vire-shadow-gold:0 0 32px rgba(228,180,72,.55);
  --vire-shadow-panel:0 8px 30px rgba(0,0,0,.28);
}

.vire-site{
  background:
    radial-gradient(1200px 600px at 20% -10%, rgba(90,47,227,.25), transparent 60%),
    radial-gradient(900px 520px at 90% 40%, rgba(58,244,211,.10), transparent 55%),
    linear-gradient(180deg, rgba(10,26,74,1), rgba(3,10,26,1));
  color:#fff;
  padding:42px 18px;
  border-radius:18px;
}

.vire-site h1,.vire-site h2,.vire-site h3{ letter-spacing:-0.02em; }
.vire-site h1{ font-size:clamp(34px,5vw,64px); margin:6px 0 12px; }
.vire-site p{ color:rgba(255,255,255,.86); font-size:16px; line-height:1.7; max-width:74ch; }

.vire-neural-host{
  position:relative;
  margin:10px 0 22px;
  border-radius:var(--vire-radius-lg);
  overflow:hidden;
  border:1px solid rgba(62,70,93,.70);
  box-shadow:var(--vire-shadow-panel);
}
.vire-neural-canvas{ display:block; width:100%; height:320px; }
@media(max-width:720px){ .vire-neural-canvas{ height:220px; } }

.vire-cta{
  display:inline-flex; align-items:center; gap:10px;
  padding:12px 16px;
  border-radius:var(--vire-radius-md);
  background:linear-gradient(135deg,var(--vire-neural-purple),var(--vire-electric-teal));
  color:#fff; text-decoration:none;
  box-shadow:var(--vire-shadow-gold);
  transition:transform .15s ease, filter .15s ease;
}
.vire-cta:hover{ transform:translateY(-1px) scale(1.01); filter:brightness(1.03); }
CSS

# -----------------------------
# 4) Local WP: install/import pages + enqueue assets
# -----------------------------
cat <<'SH' > "$V5/wp/local_wp_apply.sh"
#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/../bin/common.sh"

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
LOCAL_WP_DIR="$ROOT_DIR/../vireoka_local"

WP_CONTAINER="vireoka_wp"
DB_CONTAINER="vireoka_db"

echo "�� Applying Vire V5 to LOCAL WordPress (Docker)"
need_cmd docker

container_running "$WP_CONTAINER" || die "WordPress container not running: $WP_CONTAINER"
container_running "$DB_CONTAINER" || die "DB container not running: $DB_CONTAINER"

ensure_wp_cli_in_container "$WP_CONTAINER"

# Make sure WP is installed (if fresh)
if ! docker exec "$WP_CONTAINER" sh -lc "wp core is-installed --allow-root >/dev/null 2>&1"; then
  echo "🧱 WP not installed in container volume — doing minimal install"
  docker exec "$WP_CONTAINER" sh -lc "wp core install --url=http://localhost:8085 --title='Vireoka Local' --admin_user=admin --admin_password=admin --admin_email=admin@local.test --skip-email --allow-root"
fi

# Activate shared theme (you said: vireoka_core is universal)
docker exec "$WP_CONTAINER" sh -lc "wp theme activate vireoka_core --allow-root" || true

# Import generated pages (Gutenberg HTML as page content)
PAGES_DIR="$ROOT_DIR/v5/outputs/pages"
[ -d "$PAGES_DIR" ] || die "Missing pages dir: $PAGES_DIR (run export first)"

echo "📄 Creating/Updating pages in WP"
for f in "$PAGES_DIR"/*.html; do
  slug="$(basename "$f" .html)"
  title="$(python3 - <<PY
import os
s=os.path.basename("$f").replace(".html","")
print(s.replace("-"," ").title())
PY
)"
  content="$(cat "$f")"

  # If page exists, update; else create
  if docker exec "$WP_CONTAINER" sh -lc "wp post list --post_type=page --name='$slug' --field=ID --allow-root | grep -E '^[0-9]+' >/dev/null 2>&1"; then
    id="$(docker exec "$WP_CONTAINER" sh -lc "wp post list --post_type=page --name='$slug' --field=ID --allow-root | head -n1")"
    docker exec "$WP_CONTAINER" sh -lc "wp post update $id --post_title='$title' --post_content=\"$(printf %s "$content" | sed 's/"/\\"/g')\" --post_status=publish --allow-root"
  else
    docker exec "$WP_CONTAINER" sh -lc "wp post create --post_type=page --post_title='$title' --post_name='$slug' --post_status=publish --post_content=\"$(printf %s "$content" | sed 's/"/\\"/g')\" --allow-root"
  fi
done

# Set Home page
HOME_ID="$(docker exec "$WP_CONTAINER" sh -lc "wp post list --post_type=page --name='home' --field=ID --allow-root | head -n1" || true)"
if [ -n "${HOME_ID:-}" ]; then
  docker exec "$WP_CONTAINER" sh -lc "wp option update show_on_front page --allow-root"
  docker exec "$WP_CONTAINER" sh -lc "wp option update page_on_front $HOME_ID --allow-root"
fi

# Upload assets into wp-content/uploads/vire-v5 so the theme can enqueue if desired
echo "🧱 Publishing V5 assets into uploads/"
docker exec "$WP_CONTAINER" sh -lc "mkdir -p /var/www/html/wp-content/uploads/vire-v5"

docker cp "$ROOT_DIR/v5/wp/vire-v5.css" "$WP_CONTAINER:/var/www/html/wp-content/uploads/vire-v5/vire-v5.css"
docker cp "$ROOT_DIR/v5/wp/neural-canvas.js" "$WP_CONTAINER:/var/www/html/wp-content/uploads/vire-v5/neural-canvas.js"

echo "✅ Local WP ready: http://localhost:8085"
SH
chmod +x "$V5/wp/local_wp_apply.sh"

# -----------------------------
# 5) Deploy to Hostinger: files + DB push
# -----------------------------
cat <<'SH' > "$V5/deploy/deploy_to_hostinger.sh"
#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/../bin/common.sh"

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
TOOLS="$ROOT_DIR/../vireoka-tools"

[ -d "$TOOLS" ] || die "Missing tools dir: $TOOLS"
[ -f "$TOOLS/vconfig.sh" ] || die "Missing vconfig.sh in: $TOOLS"

echo "🚚 Deploying to Hostinger (files via vsync + DB push)"

# 1) Files (themes/plugins/uploads) using your Vireoka Sync Suite
bash "$TOOLS/vsync.sh" all

# 2) DB push (local → remote)
bash "$TOOLS/vdb-push.sh"

echo "✅ Deploy complete."
SH
chmod +x "$V5/deploy/deploy_to_hostinger.sh"

# Create vdb-push.sh in vireoka-tools (EOF-safe)
cat <<'SH' > "$TOOLS_DIR/vdb-push.sh"
#!/usr/bin/env bash
set -euo pipefail

BASE_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$BASE_DIR/vconfig.sh"

DB_CONTAINER="vireoka_db"

if ! docker ps --format '{{.Names}}' | grep -q "^$DB_CONTAINER$"; then
  echo "❌ Database container '$DB_CONTAINER' not running."
  exit 1
fi

echo "✅ Using DB container: $DB_CONTAINER"

TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
LOCAL_DUMP="$BASE_DIR/vireoka_local_${TIMESTAMP}.sql"
REMOTE_DUMP="/tmp/vireoka_local_${TIMESTAMP}.sql"

echo "⬆️  Exporting LOCAL DB from container as root..."
docker exec -i "$DB_CONTAINER" sh -lc "mysqldump -uroot -proot --no-tablespaces wordpress" > "$LOCAL_DUMP"

echo "⬆️  Uploading dump to remote..."
scp -P "$REMOTE_PORT" "$LOCAL_DUMP" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_DUMP" >/dev/null

echo "⬆️  Importing dump on remote (Hostinger-safe)..."
ssh -p "$REMOTE_PORT" "$REMOTE_USER@$REMOTE_HOST" "
  cd '$REMOTE_ROOT'
  DB_NAME=\$(php -r \"include 'wp-config.php'; echo DB_NAME;\")
  DB_USER=\$(php -r \"include 'wp-config.php'; echo DB_USER;\")
  DB_PASS=\$(php -r \"include 'wp-config.php'; echo DB_PASSWORD;\")
  DB_HOST=\$(php -r \"include 'wp-config.php'; echo DB_HOST;\")
  /usr/bin/mariadb -h \"\$DB_HOST\" -u \"\$DB_USER\" -p\"\$DB_PASS\" \"\$DB_NAME\" < '$REMOTE_DUMP'
  rm -f '$REMOTE_DUMP'
"

rm -f "$LOCAL_DUMP"

echo "✅ LOCAL → PROD DB push COMPLETE"
SH
chmod +x "$TOOLS_DIR/vdb-push.sh"

# -----------------------------
# 6) Verify + screenshot report
# -----------------------------
cat <<'SH' > "$V5/verify/verify_and_report.sh"
#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/../bin/common.sh"

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
TOOLS="$ROOT_DIR/../vireoka-tools"
source "$TOOLS/vconfig.sh"

LIVE_BASE="https://vireoka.com"
OUT_DIR="$ROOT_DIR/v5/report"
mkdir -p "$OUT_DIR"

echo "🧪 Verifying LIVE site..."
need_cmd curl

# Basic checks
http_ok "$LIVE_BASE" || die "Live homepage not reachable: $LIVE_BASE"
echo "✅ Live homepage OK: $LIVE_BASE"

# Optional: list key pages via WP-CLI on remote if present
echo "🔎 Checking remote WP-CLI (best effort)..."
ssh -p "$REMOTE_PORT" "$REMOTE_USER@$REMOTE_HOST" "command -v wp >/dev/null 2>&1 && cd '$REMOTE_ROOT' && wp option get home || true" || true

# Screenshot report (prefers Playwright; falls back to chromium if available)
python3 "$ROOT_DIR/v5/report/screenshot_report.py" "$LIVE_BASE" "$OUT_DIR" || true

echo "✅ Verify/report done."
echo "📄 Report folder: $OUT_DIR"
SH
chmod +x "$V5/verify/verify_and_report.sh"

cat <<'PY' > "$V5/report/screenshot_report.py"
#!/usr/bin/env python3
import os, sys, json, time
from pathlib import Path
from datetime import datetime, timezone

def utc_now():
    return datetime.now(timezone.utc).isoformat()

def try_playwright(urls, out_dir: Path):
    try:
        from playwright.sync_api import sync_playwright
    except Exception as e:
        return False, f"playwright not available: {e}"

    shots = []
    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page(viewport={"width": 1440, "height": 900})
        for u in urls:
            fn = out_dir / (u.replace("https://", "").replace("http://", "").replace("/", "_").strip("_") + ".png")
            page.goto(u, wait_until="networkidle", timeout=60000)
            time.sleep(1.0)
            page.screenshot(path=str(fn), full_page=True)
            shots.append({"url": u, "file": fn.name})
        browser.close()
    return True, shots

def write_html(base, shots, out_dir: Path, note: str):
    html = ["<!doctype html><html><head><meta charset='utf-8'/>",
            "<meta name='viewport' content='width=device-width,initial-scale=1'/>",
            "<title>Vire V5 Screenshot Report</title>",
            "<style>body{font-family:Inter,system-ui,Segoe UI,Arial,sans-serif;background:#0A1A4A;color:#fff;margin:0} .wrap{max-width:1100px;margin:0 auto;padding:22px 14px} .card{background:rgba(27,34,53,.62);border:1px solid rgba(62,70,93,.75);border-radius:18px;padding:14px;margin:12px 0} img{max-width:100%;border-radius:12px;border:1px solid rgba(255,255,255,.12)}</style>",
            "</head><body><div class='wrap'>",
            f"<h1>Vire V5 — Screenshot Report</h1><p>Base: {base}<br/>Generated: {utc_now()}</p>",
            f"<div class='card'><strong>Note:</strong> {note}</div>"]
    for s in shots:
        html.append("<div class='card'>")
        html.append(f"<div><a style='color:#3AF4D3' href='{s['url']}'>{s['url']}</a></div>")
        html.append(f"<img src='{s['file']}' alt='screenshot'/>")
        html.append("</div>")
    html.append("</div></body></html>")
    (out_dir / "report.html").write_text("\n".join(html), encoding="utf-8")

def main():
    if len(sys.argv) < 3:
        print("Usage: screenshot_report.py <base_url> <out_dir>")
        return 1

    base = sys.argv[1].rstrip("/")
    out_dir = Path(sys.argv[2])
    out_dir.mkdir(parents=True, exist_ok=True)

    urls = [
        base + "/",
        base + "/products/",
        base + "/atmasphere-llm/",
        base + "/dating-platform-builder/",
        base + "/quantum-secure-finance/",
    ]

    ok, result = try_playwright(urls, out_dir)
    if ok:
        write_html(base, result, out_dir, "Screenshots captured with Playwright.")
        print("✅ report.html written:", out_dir / "report.html")
        return 0

    # Fallback: no screenshots, but still output a report
    write_html(base, [], out_dir, "Playwright not installed; no screenshots captured. Install with: pip install playwright && playwright install chromium")
    print("⚠️ report.html written without screenshots:", out_dir / "report.html")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
PY
chmod +x "$V5/report/screenshot_report.py"

# -----------------------------
# 7) The ONE command runner
# -----------------------------
cat <<'SH' > "$V5/vire_v5_onecmd.sh"
#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/bin/common.sh"

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"         # .../vire-agent
V5="$ROOT_DIR/v5"
REPO_ROOT="$(cd "$ROOT_DIR/.." && pwd)"              # .../vireoka_website

PROMPT="${1:-}"
PRODUCT="${2:-Vireoka Product}"
TONE="${3:-elite-neural-luxe}"

[ -n "$PROMPT" ] || die "Usage: ./vire-agent/v5/vire_v5_onecmd.sh \"<prompt>\" \"<product name>\" \"<tone>\""

echo "🧠 1) Prompt → site.json"
python3 "$V5/gen/prompt_to_site.py" "$PROMPT" "$PRODUCT" "$TONE" "$V5/outputs/site.json"

echo "🧱 2) site.json → Gutenberg pages"
python3 "$V5/wp/wp_static_export.py"

echo "🐳 3) Ensure local WP Docker is up"
need_cmd docker
cd "$REPO_ROOT/vireoka_local"
docker compose up -d

echo "�� 4) Apply pages + theme to local WP"
cd "$REPO_ROOT"
bash "$V5/wp/local_wp_apply.sh"

echo "🚚 5) Deploy to Hostinger (files + DB)"
bash "$V5/deploy/deploy_to_hostinger.sh"

echo "🧪 6) Verify + screenshot report"
bash "$V5/verify/verify_and_report.sh"

echo
echo "✅ Vire V5 complete."
echo "Local: http://localhost:8085"
echo "Live:  https://vireoka.com"
echo "Report: vire-agent/v5/report/report.html"
SH
chmod +x "$V5/vire_v5_onecmd.sh"
