#!/usr/bin/env python3
import json, re, datetime
from pathlib import Path

def utc_now_iso():
    return datetime.datetime.now(datetime.timezone.utc).isoformat()

def slugify(s: str) -> str:
    s = (s or "").strip().lower()
    s = re.sub(r"[^a-z0-9\s-]", "", s)
    s = re.sub(r"\s+", "-", s).strip("-")
    return s or "page"

def page_html(title: str, product: str, tone: str):
    # Gutenberg wrapper: group block
    return f"""<!-- wp:group {{"className":"vire-site vire-product--{slugify(product)} vire-tone--{slugify(tone)}","layout":{{"type":"constrained"}}}} -->
<div class="wp-block-group vire-site vire-product--{slugify(product)} vire-tone--{slugify(tone)}">
  <!-- wp:heading {{"level":1}} -->
  <h1>{title}</h1>
  <!-- /wp:heading -->

  <!-- wp:paragraph -->
  <p><strong>{product}</strong> — generated by Vire V5 at {utc_now_iso()}.</p>
  <!-- /wp:paragraph -->

  <!-- wp:html -->
  <div class="vire-neural-host"><canvas class="vire-neural-canvas" aria-hidden="true"></canvas></div>
  <!-- /wp:html -->

  <!-- wp:columns -->
  <div class="wp-block-columns">
    <!-- wp:column -->
    <div class="wp-block-column">
      <!-- wp:heading {{"level":2}} --><h2>Why this matters</h2><!-- /wp:heading -->
      <!-- wp:paragraph --><p>Premium, enterprise-ready AI agent platform branding with Elite Neural Luxe design tokens.</p><!-- /wp:paragraph -->
    </div>
    <!-- /wp:column -->
    <!-- wp:column -->
    <div class="wp-block-column">
      <!-- wp:heading {{"level":2}} --><h2>Next steps</h2><!-- /wp:heading -->
      <!-- wp:list -->
      <ul>
        <li>Deploy to Hostinger</li>
        <li>Verify live pages</li>
        <li>Generate screenshot report</li>
      </ul>
      <!-- /wp:list -->
      <!-- wp:paragraph --><p><a class="vire-cta" href="/contact/">Request demo</a></p><!-- /wp:paragraph -->
    </div>
    <!-- /wp:column -->
  </div>
  <!-- /wp:columns -->
</div>
<!-- /wp:group -->
"""

def main():
    site_path = Path("vire-agent/v5/outputs/site.json")
    if not site_path.exists():
        raise SystemExit("❌ Missing vire-agent/v5/outputs/site.json (generate it first).")

    site = json.loads(site_path.read_text(encoding="utf-8"))
    product = site.get("product_name", "Vireoka Product")
    tone = site.get("tone", "elite-neural-luxe")
    pages = site.get("pages", ["Home"])

    out_dir = Path("vire-agent/v5/outputs/pages")
    out_dir.mkdir(parents=True, exist_ok=True)

    created = []
    for title in pages:
        slug = slugify(title)
        p = out_dir / f"{slug}.html"
        p.write_text(page_html(title, product, tone), encoding="utf-8")
        created.append(str(p))

    print("✅ Exported pages:")
    for c in created:
        print(" -", c)

if __name__ == "__main__":
    main()
