<?php
/**
 * Plugin Name: Vire REST Bridge (v2)
 * Description: Vire admin endpoints (read+controlled write) for sync approvals, content, and monitoring.
 */

if (!defined('ABSPATH')) exit;

function vire_status_dir() {
  // public_html/_sync_status
  return ABSPATH . '_sync_status/';
}

function vire_read_json($file) {
  $p = vire_status_dir() . $file;
  return file_exists($p) ? json_decode(file_get_contents($p), true) : null;
}

function vire_write_json($file, $data) {
  $dir = vire_status_dir();
  if (!file_exists($dir)) @mkdir($dir, 0755, true);
  $p = $dir . $file;
  file_put_contents($p, json_encode($data, JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));
  return $p;
}

function vire_now_iso() {
  return gmdate('Y-m-d\TH:i:s\Z');
}

/**
 * Optional LLM adapter (OpenAI compatible)
 * Reads key from env OPENAI_API_KEY if available.
 * If missing, returns deterministic fallback content.
 */
function vire_llm_generate($prompt, $mode = 'content') {
  $key = getenv('OPENAI_API_KEY');
  if (!$key) {
    // Fallback template (deterministic)
    return [
      'title' => 'Draft: ' . substr(trim($prompt), 0, 60),
      'slug' => sanitize_title(substr(trim($prompt), 0, 60)),
      'excerpt' => 'Auto-generated fallback (no LLM key configured).',
      'content' =>
        "<h2>Executive Summary</h2><p>" . esc_html($prompt) . "</p>" .
        "<h2>Key Ideas</h2><ul><li>Agentic workflows</li><li>Security posture</li><li>Operational reliability</li></ul>" .
        "<h2>Implementation Notes</h2><p>Replace this content with LLM output once OPENAI_API_KEY is configured.</p>"
    ];
  }

  // Minimal OpenAI chat call (kept simple; you can later move this to your own gateway)
  $body = [
    'model' => 'gpt-4o-mini',
    'messages' => [
      ['role' => 'system', 'content' => "You are Vire. Produce WordPress-ready HTML with H2/H3, plus title, slug, excerpt."],
      ['role' => 'user', 'content' => $prompt],
    ],
    'temperature' => 0.6
  ];

  $resp = wp_remote_post('https://api.openai.com/v1/chat/completions', [
    'headers' => [
      'Authorization' => 'Bearer ' . $key,
      'Content-Type' => 'application/json'
    ],
    'body' => json_encode($body),
    'timeout' => 30
  ]);

  if (is_wp_error($resp)) {
    return ['error' => $resp->get_error_message()];
  }

  $json = json_decode(wp_remote_retrieve_body($resp), true);
  $text = $json['choices'][0]['message']['content'] ?? '';
  if (!$text) return ['error' => 'Empty LLM output'];

  // Expect the model to output a simple JSON block at top OR we fallback to HTML-only
  // Try to parse JSON if present, else wrap HTML.
  $maybe = json_decode($text, true);
  if (is_array($maybe) && isset($maybe['content'])) return $maybe;

  return [
    'title' => 'Vire Draft',
    'slug' => 'vire-draft-' . time(),
    'excerpt' => 'Generated by Vire LLM.',
    'content' => $text
  ];
}

function vire_permission_admin() {
  return current_user_can('manage_options');
}

add_action('rest_api_init', function () {

  // ------------------------
  // 1) Read-only artifacts
  // ------------------------
  register_rest_route('vire', '/status', [
    'methods' => 'GET',
    'callback' => fn() => vire_read_json('status.json'),
    'permission_callback' => 'vire_permission_admin',
  ]);

  register_rest_route('vire', '/plan', [
    'methods' => 'GET',
    'callback' => fn() => vire_read_json('resolution_plan.json'),
    'permission_callback' => 'vire_permission_admin',
  ]);

  register_rest_route('vire', '/explain', [
    'methods' => 'GET',
    'callback' => fn() => vire_read_json('ai_conflicts_report.json'),
    'permission_callback' => 'vire_permission_admin',
  ]);

  // ------------------------
  // 2) Approvals (Apply/Reject)
  // Writes approval.json for a local worker to act upon
  // ------------------------
  register_rest_route('vire', '/approval', [
    'methods' => 'POST',
    'callback' => function($req){
      $action = $req->get_param('action'); // apply|reject
      if (!in_array($action, ['apply','reject'], true)) {
        return new WP_REST_Response(['ok'=>false,'error'=>'Invalid action'], 400);
      }
      $plan = vire_read_json('resolution_plan.json');
      $data = [
        'ok' => true,
        'action' => $action,
        'approved_at' => vire_now_iso(),
        'approved_by' => wp_get_current_user()->user_login,
        'plan_summary' => [
          'generated_at' => $plan['generated_at'] ?? null,
          'conflicts_found' => $plan['conflicts_found'] ?? null,
          'recommendation' => $plan['recommendation'] ?? null,
        ],
      ];
      vire_write_json('approval.json', $data);
      return $data;
    },
    'permission_callback' => 'vire_permission_admin',
  ]);

  // ------------------------
  // 3) Plugin Risk Scoring
  // Offline heuristics (designed to be extended with CVE feeds later)
  // ------------------------
  register_rest_route('vire', '/plugin-risk', [
    'methods' => 'GET',
    'callback' => function(){
      require_once ABSPATH . 'wp-admin/includes/plugin.php';
      $all = get_plugins();
      $active = array_flip(get_option('active_plugins', []));
      $updates = get_site_transient('update_plugins');
      $update_resp = is_object($updates) ? ($updates->response ?? []) : [];

      // Configurable “known risky” slugs (adjust as you learn)
      $risky = [
        'revslider/revslider.php',
        'wp-file-manager/file_folder_manager.php',
      ];

      $rows = [];
      foreach ($all as $path => $info) {
        $is_active = isset($active[$path]);
        $has_update = isset($update_resp[$path]);
        $score = 0;
        $reasons = [];

        // Baseline
        $score += $is_active ? 10 : 2;

        // Update available => risk up
        if ($has_update) { $score += 25; $reasons[] = 'Update available'; }

        // Known risky list
        if (in_array($path, $risky, true)) { $score += 35; $reasons[] = 'Known risky plugin (local list)'; }

        // Check vendor/autoload missing (common fatal error, like RankMath missing vendor/)
        $plugin_dir = WP_PLUGIN_DIR . '/' . dirname($path);
        if (file_exists($plugin_dir . '/vendor') && !file_exists($plugin_dir . '/vendor/autoload.php')) {
          $score += 20; $reasons[] = 'vendor/ exists but vendor/autoload.php missing';
        }

        // Clamp + grade
        $score = min(100, $score);
        $grade = $score >= 70 ? 'High' : ($score >= 40 ? 'Medium' : 'Low');

        $rows[] = [
          'plugin' => $info['Name'] ?? $path,
          'path' => $path,
          'version' => $info['Version'] ?? '',
          'active' => $is_active,
          'update_available' => $has_update,
          'score' => $score,
          'grade' => $grade,
          'reasons' => $reasons
        ];
      }

      // Sort highest risk first
      usort($rows, fn($a,$b) => $b['score'] <=> $a['score']);
      return ['ok'=>true, 'count'=>count($rows), 'items'=>$rows];
    },
    'permission_callback' => 'vire_permission_admin',
  ]);

  // ------------------------
  // 4) Editorial Calendar (stored in wp_option)
  // ------------------------
  register_rest_route('vire', '/editorial', [
    'methods' => 'GET',
    'callback' => function(){
      $cal = get_option('vire_editorial_calendar', ['items'=>[]]);
      return ['ok'=>true, 'calendar'=>$cal];
    },
    'permission_callback' => 'vire_permission_admin',
  ]);

  register_rest_route('vire', '/editorial', [
    'methods' => 'POST',
    'callback' => function($req){
      $cal = get_option('vire_editorial_calendar', ['items'=>[]]);
      $item = $req->get_json_params();
      if (!is_array($item)) $item = [];
      $item['id'] = $item['id'] ?? ('cal_' . time());
      $item['updated_at'] = vire_now_iso();
      $cal['items'] = $cal['items'] ?? [];
      $cal['items'][] = $item;
      update_option('vire_editorial_calendar', $cal, false);
      return ['ok'=>true, 'added'=>$item];
    },
    'permission_callback' => 'vire_permission_admin',
  ]);

  // ------------------------
  // 5) Prompt -> Draft -> Publish
  // ------------------------
  register_rest_route('vire', '/content/generate', [
    'methods' => 'POST',
    'callback' => function($req){
      $prompt = (string)($req->get_param('prompt') ?? '');
      $mode = (string)($req->get_param('mode') ?? 'content');
      if (!$prompt) return new WP_REST_Response(['ok'=>false,'error'=>'prompt required'], 400);
      $gen = vire_llm_generate($prompt, $mode);
      return ['ok'=>true,'generated'=>$gen];
    },
    'permission_callback' => 'vire_permission_admin',
  ]);

  register_rest_route('vire', '/content/draft', [
    'methods' => 'POST',
    'callback' => function($req){
      $payload = $req->get_json_params();
      if (!is_array($payload)) $payload = [];
      $title = $payload['title'] ?? 'Vire Draft';
      $content = $payload['content'] ?? '';
      $excerpt = $payload['excerpt'] ?? '';

      $post_id = wp_insert_post([
        'post_title' => wp_strip_all_tags($title),
        'post_content' => $content,
        'post_excerpt' => wp_strip_all_tags($excerpt),
        'post_status' => 'draft',
        'post_type' => 'post',
      ], true);

      if (is_wp_error($post_id)) {
        return new WP_REST_Response(['ok'=>false,'error'=>$post_id->get_error_message()], 500);
      }

      return ['ok'=>true,'post_id'=>$post_id,'edit_url'=>get_edit_post_link($post_id,'raw')];
    },
    'permission_callback' => 'vire_permission_admin',
  ]);

  register_rest_route('vire', '/content/publish', [
    'methods' => 'POST',
    'callback' => function($req){
      $id = (int)$req->get_param('post_id');
      if (!$id) return new WP_REST_Response(['ok'=>false,'error'=>'post_id required'], 400);

      $r = wp_update_post(['ID'=>$id,'post_status'=>'publish'], true);
      if (is_wp_error($r)) return new WP_REST_Response(['ok'=>false,'error'=>$r->get_error_message()], 500);

      return ['ok'=>true,'post_id'=>$id,'url'=>get_permalink($id)];
    },
    'permission_callback' => 'vire_permission_admin',
  ]);

  // ------------------------
  // 6) Monitor
  // ------------------------
  register_rest_route('vire', '/monitor', [
    'methods' => 'GET',
    'callback' => function(){
      require_once ABSPATH . 'wp-admin/includes/update.php';
      require_once ABSPATH . 'wp-admin/includes/plugin.php';

      $core = get_site_transient('update_core');
      $plugins = get_site_transient('update_plugins');

      $core_updates = is_object($core) ? count($core->updates ?? []) : 0;
      $plugin_updates = is_object($plugins) ? count($plugins->response ?? []) : 0;

      $data = [
        'ok' => true,
        'timestamp' => vire_now_iso(),
        'core_updates' => $core_updates,
        'plugin_updates' => $plugin_updates,
        'siteurl' => get_option('siteurl'),
        'home' => get_option('home'),
      ];

      // Include last sync (if present)
      $status = vire_read_json('status.json');
      if ($status) $data['last_sync'] = $status;

      return $data;
    },
    'permission_callback' => 'vire_permission_admin',
  ]);

});
