import os, json, pathlib

BASE = pathlib.Path(__file__).parent
PAGES = BASE / "pages"
PAGES.mkdir(exist_ok=True)

def export_page(title):
    slug = title.lower().replace(" ", "-")
    html = f"""
<!-- wp:group -->
<div class="wp-block-group">
  <h1>{title}</h1>
  <p>Generated by Vire AI Agent for Vireoka.</p>
</div>
<!-- /wp:group -->
"""
    (PAGES / f"{slug}.html").write_text(html)

if __name__ == "__main__":
    if not os.path.exists("site.json"):
        raise SystemExit("❌ site.json missing")

    site = json.load(open("site.json"))
    for page in site["pages"]:
        export_page(page)

    print("✅ Gutenberg pages exported:", len(site["pages"]))
